/**
 * AppleCider's icon names → lucide-react component names.
 *
 * The two sets overlap almost entirely because both are drawn from the same
 * 24px stroked vocabulary, so most of this is a straight rename. Anything not
 * listed falls back to `Circle`, which is visible and obviously a placeholder
 * rather than quietly rendering nothing.
 */

const MAP: Record<string, string> = {
  // navigation
  search: 'Search',
  plus: 'Plus',
  minus: 'Minus',
  x: 'X',
  check: 'Check',
  chevronDown: 'ChevronDown',
  chevronUp: 'ChevronUp',
  chevronLeft: 'ChevronLeft',
  chevronRight: 'ChevronRight',
  chevronsLeft: 'ChevronsLeft',
  chevronsRight: 'ChevronsRight',
  arrowLeft: 'ArrowLeft',
  arrowRight: 'ArrowRight',
  arrowUp: 'ArrowUp',
  arrowDown: 'ArrowDown',
  arrow: 'ArrowRight',
  menu: 'Menu',
  moreH: 'MoreHorizontal',
  moreV: 'MoreVertical',
  external: 'ExternalLink',
  maximize: 'Maximize2',
  command: 'Command',
  filter: 'Filter',
  sortDesc: 'ArrowDownWideNarrow',

  // objects and people
  user: 'User',
  users: 'Users',
  home: 'Home',
  settings: 'Settings',
  bell: 'Bell',
  heart: 'Heart',
  star: 'Star',
  starFill: 'Star',
  calendar: 'Calendar',
  clock: 'Clock',
  mail: 'Mail',
  phone: 'Phone',
  camera: 'Camera',
  image: 'Image',
  file: 'File',
  folder: 'Folder',
  trash: 'Trash2',
  edit: 'Pencil',
  copy: 'Copy',
  share: 'Share2',
  download: 'Download',
  upload: 'Upload',
  link: 'Link',
  lock: 'Lock',
  unlock: 'LockOpen',
  eye: 'Eye',
  eyeOff: 'EyeOff',
  play: 'Play',
  pause: 'Pause',
  info: 'Info',
  alert: 'TriangleAlert',
  help: 'CircleHelp',
  card: 'CreditCard',
  cart: 'ShoppingCart',
  tag: 'Tag',
  pin: 'MapPin',
  send: 'Send',
  message: 'MessageSquare',
  thumbsUp: 'ThumbsUp',
  bookmark: 'Bookmark',
  zap: 'Zap',
  box: 'Package',
  database: 'Database',
  code: 'Code',
  terminal: 'Terminal',
  layers: 'Layers',
  sliders: 'SlidersHorizontal',
  logout: 'LogOut',
  moon: 'Moon',
  sun: 'Sun',
  wifi: 'Wifi',
  battery: 'BatteryFull',
  list: 'List',
  inbox: 'Inbox',
  bulb: 'Lightbulb',
  target: 'Target',
  flag: 'Flag',
  gift: 'Gift',
  key: 'Key',
  shield: 'Shield',
  rocket: 'Rocket',
  sparkle: 'Sparkles',
  apple: 'Apple',
  scissors: 'Scissors',
  magic: 'Wand',
  history: 'History',
  keyboard: 'Keyboard',
  github: 'Github',
  refresh: 'RefreshCw',
  undo: 'Undo2',
  redo: 'Redo2',
  grid: 'Grid3x3',
  columns: 'Columns3',
  rows: 'Rows3',
  frame: 'Frame',
  square: 'Square',
  circle: 'Circle',
  triangle: 'Triangle',
  type: 'Type',
  pen: 'PenLine',
  crop: 'Crop',
  sticky: 'StickyNote',
  hand: 'Hand',
  cursor: 'MousePointer2',
  chartBar: 'ChartColumn',
  chartLine: 'ChartLine',
  chartPie: 'ChartPie',
}

export const lucideName = (icon: string): string => MAP[icon] ?? 'Circle'

/** `starFill` is lucide's `Star` with a fill — worth keeping the distinction. */
export const isFilled = (icon: string): boolean => icon === 'starFill'
